management:
  # Endpoints configuration
  endpoints:
    # Enable all endpoints by default
    enabled: true
    
    # Web exposure configuration
    web:
      # Expose essential endpoints by default
      exposure: "health,info,metrics,prometheus"
      # Base path for actuator endpoints
      base-path: /actuator
      # Include details in responses
      include-details: true
  
  # Metrics configuration
  metrics:
    # Enable metrics collection
    enabled: true
    # Tags to add to all metrics
    tags:
      application: ${spring.application.name:application}
      environment: ${spring.profiles.active:default}
  
  # Health configuration
  health:
    # Show details in health endpoint
    show-details: always
    # Show components in health endpoint
    show-components: true
    
    # Disk space configuration
    disk-space:
      # Enable disk space health check
      enabled: true
      # Threshold for disk space health check
      threshold: 10MB

# Logging configuration for tracing
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{X-Transaction-Id:-}]"
